In [1]:
import pandas as pd
import os
from dask import dataframe as dd

In [2]:
# What is the current working directory?
os.getcwd()

'g:\\Shared drives\\URSC645_S2023\\Tasks\\ObtainData\\WorkNPR'

## Read in a Large CSV file

Help from Google Searches:
- https://medium.com/analytics-vidhya/optimized-ways-to-read-large-csvs-in-python-ab2b36a7914e 

Dask documentation:
- https://docs.dask.org/en/latest/dataframe.html
- help with Dask: https://www.youtube.com/watch?v=jstCmSD_LAs

In [3]:
# Read in data and set data type to object (which is tha same as a string)
# The csv file can have mixed data types and this will allow us to read in the data with fewer errors 
dask_df = dd.read_csv('..\SourceData\OpenFEMA\IndividualsAndHouseholdsProgramValidRegistrations (1).csv', 
                    low_memory=False,
                    dtype= 'object')

In [4]:
dask_df

Dask DataFrame Structure:
                incidentType declarationDate disasterNumber  county damagedStateAbbreviation damagedCity damagedZipCode applicantAge householdComposition occupantsUnderTwo occupants2to5 occupants6to18 occupants19to64 occupants65andOver grossIncome ownRent primaryResidence residenceType homeOwnersInsurance floodInsurance registrationMethod ihpReferral ihpEligible ihpAmount fipAmount haReferral haEligible haAmount haStatus onaReferral onaEligible onaAmount utilitiesOut homeDamage autoDamage emergencyNeeds foodNeed shelterNeed accessFunctionalNeeds sbaEligible sbaApproved inspnIssued inspnReturned habitabilityRepairsRequired   rpfvl   ppfvl renterDamageLevel destroyed waterLevel highWaterLocation floodDamage floodDamageAmount foundationDamage foundationDamageAmount roofDamage roofDamageAmount tsaEligible tsaCheckedIn rentalAssistanceEligible rentalAssistanceAmount repairAssistanceEligible repairAmount replacementAssistanceEligible replacementAmount personalPropertyEligible personalPropertyAmount  ihpMax   haMax  onaMax lastRefresh      id
npartitions=119
                      object          object         object  object                   object      object         object       object               object            object        object         object          object             object      object  object           object        object              object         object             object      object      object    object    object     object     object   object   object      object      object    object       object     object     object         object   object      object                object      object      object      object        object                      object  object  object            object    object     object            object      object            object           object                 object     object           object      object       object                   object                 object                   object       object                        object            object                   object                 object  object  object  object      object  object
                         ...             ...            ...     ...                      ...         ...            ...          ...                  ...               ...           ...            ...             ...                ...         ...     ...              ...           ...                 ...            ...                ...         ...         ...       ...       ...        ...        ...      ...      ...         ...         ...       ...          ...        ...        ...            ...      ...         ...                   ...         ...         ...         ...           ...                         ...     ...     ...               ...       ...        ...               ...         ...               ...              ...                    ...        ...              ...         ...          ...                      ...                    ...                      ...          ...                           ...               ...                      ...                    ...     ...     ...     ...         ...     ...
...                      ...             ...            ...     ...                      ...         ...            ...          ...                  ...               ...           ...            ...             ...                ...         ...     ...              ...           ...                 ...            ...                ...         ...         ...       ...       ...        ...        ...      ...      ...         ...         ...       ...          ...        ...        ...            ...      ...         ...                   ...         ...         ...         ...           ...                         ...     ...     ...               ...       ...        ...               ...         ...               ...              ...                    ...        ...              ...         ...          ...                      ...                    ...                      ...          ...                           ...               ...                      ...                    ...     ...     ...     ...         ...     ...
                         ...             ...            ...     ...                      ...         ...            ...          ...                  ...               ...           ...            ...             ...                ...         ...     ...              ...           ...                 ...            ...                ...         ...         ...       ...       ...        ...        ...      ...      ...         ...         ...       ...          ...        ...        ...            ...      ...         ...                   ...         ...         ...         ...           ...                         ...     ...     ...               ...       ...        ...               ...         ...               ...              ...                    ...        ...              ...         ...          ...                      ...                    ...                      ...          ...                           ...               ...                      ...                    ...     ...     ...     ...         ...     ...
                         ...             ...            ...     ...                      ...         ...            ...          ...                  ...               ...           ...            ...             ...                ...         ...     ...              ...           ...                 ...            ...                ...         ...         ...       ...       ...        ...        ...      ...      ...         ...         ...       ...          ...        ...        ...            ...      ...         ...                   ...         ...         ...         ...           ...                         ...     ...     ...               ...       ...        ...               ...         ...               ...              ...                    ...        ...              ...         ...          ...                      ...                    ...                      ...          ...                           ...               ...                      ...                    ...     ...     ...     ...         ...     ...
Dask Name: read-csv, 1 graph layer

In [5]:
dask_df.head(3)

,incidentType,declarationDate,disasterNumber,county,damagedStateAbbreviation,damagedCity,damagedZipCode,applicantAge,householdComposition,occupantsUnderTwo,...,repairAmount,replacementAssistanceEligible,replacementAmount,personalPropertyEligible,personalPropertyAmount,ihpMax,haMax,onaMax,lastRefresh,id
0,Hurricane,2017-09-10T00:00:00.000Z,4337,Miami-Dade (County),FL,MIAMI,33125,65+,1,0,...,0.00,0,0.00,0,0.00,0,0,0,2022-11-22T01:54:36.000Z,f6747d1f-44ae-4efc-9cb1-124a3b7cc3ae
1,Hurricane,2017-09-10T00:00:00.000Z,4337,Orange (County),FL,APOPKA,32703,19-34,3,1,...,0.00,0,0.00,0,0.00,0,0,0,2022-11-22T01:54:36.000Z,8775c507-3d9d-4913-b1aa-97aba05cef61
2,Hurricane,2017-09-10T00:00:00.000Z,4337,Lee (County),FL,NORTH FORT MYERS,33917,19-34,1,0,...,0.00,0,0.00,0,0.00,0,0,0,2022-11-22T01:54:36.000Z,130d56b0-3af8-4a0d-99ba-79d6336d239b

#### Select a smaller subset of the data
It is difficult to develope new code on a large dataset.

In [21]:
# locate by disaster number and county
condition1 = (dask_df['disasterNumber'] == '1791')
condition2 = (dask_df['county'] == 'Galveston (County)')
# This step will also convert the dask dataframe to a pandas dataframe
drnum_county_df = dask_df.loc[condition1 & condition2].compute()

In [25]:
drnum_county_df.head()

,incidentType,declarationDate,disasterNumber,county,damagedStateAbbreviation,damagedCity,damagedZipCode,applicantAge,householdComposition,occupantsUnderTwo,...,repairAmount,replacementAssistanceEligible,replacementAmount,personalPropertyEligible,personalPropertyAmount,ihpMax,haMax,onaMax,lastRefresh,id
200,Hurricane,2008-09-13T00:00:00.000Z,1791,Galveston (County),TX,SAN LEON,77539,50-64,2,0,...,0.00,0,0.00,0,0.00,0,0,0,2022-11-22T00:31:29.000Z,916c46cb-3d85-4656-a8dc-f05f505fa9d8
216,Hurricane,2008-09-13T00:00:00.000Z,1791,Galveston (County),TX,LEAGUE CITY,77573,35-49,1,0,...,0.00,0,0.00,0,0.00,0,0,0,2022-11-22T00:31:29.000Z,4f067d1d-5be8-405b-9421-3dbe360d6460
222,Hurricane,2008-09-13T00:00:00.000Z,1791,Galveston (County),TX,TEXAS CITY,77590,50-64,2,0,...,0.00,0,0.00,0,0.00,0,0,0,2022-11-22T00:31:29.000Z,d4d386ac-5c00-457d-936a-2993a6157f09
229,Hurricane,2008-09-13T00:00:00.000Z,1791,Galveston (County),TX,PORT BOLIVAR,77650,50-64,1,0,...,0.00,0,0.00,1,2441.06,0,0,0,2022-11-22T00:31:29.000Z,07fd540c-79fe-4d60-bd7e-eb3996652c5f
242,Hurricane,2008-09-13T00:00:00.000Z,1791,Galveston (County),TX,GALVESTON,77550,65+,5,0,...,0.00,0,0.00,0,0.00,0,0,0,2022-11-22T00:31:29.000Z,2da2b8b8-bad8-4b4d-876e-d0b27030cfa2

In [26]:
drnum_county_df.groupby('county').size()

county
Galveston (County)    72214
dtype: int64

## Descriptive Statistics For Key Variables
Descriptive statistics depends on the variable type.

Variable types include:
- Object (String)
- Numeric (Integer, Float)
     - Integer (1 ,2 ,3 4, 5, 6, 7, 8, 9, 10)
     - Float (1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0)
- Time (Datetime)
        - Datetime (2020-01-01 00:00:00)
- Boolean (True, False)

In [30]:
# What is the variable type?
drnum_county_df[['occupantsUnderTwo']].dtypes

occupantsUnderTwo    object
dtype: object

In [31]:
# Look at descriptive statistics for the data
drnum_county_df[['occupantsUnderTwo']].describe()

       occupantsUnderTwo
count              72214
unique                 5
top                    0
freq               67737

In [32]:
# Group by variable to see the number of unique values
drnum_county_df.groupby('occupantsUnderTwo').size()

occupantsUnderTwo
0    67737
1     4217
2      250
3        9
4        1
dtype: int64

In [33]:
# convert variable to integer
drnum_county_df['occupantsUnderTwo'] = drnum_county_df['occupantsUnderTwo'].astype(int)

In [34]:
# Look at descriptive statistics for the data
drnum_county_df[['occupantsUnderTwo']].describe().T

                     count      mean       std  min  25%  50%  75%  max
occupantsUnderTwo  72214.0  0.065749  0.263182  0.0  0.0  0.0  0.0  4.0

### Make a function to clean variables
Create a function to clean variables. This function can be used with any dataset and set of variables

In [50]:
def clean_variables(df, var_list, var_type):
    '''
    This function will convert a list of 
    variables to a specified data type

    '''

    # Check variables 
    for var in var_list:
        print('Variable: ' + str(var))
        # check if variable is a string
        if df[var].dtype == object:
            print('Variable is an object (string)')
            # Check categories
            # Group by variable to see the number of unique values
            print(df.groupby(var).size())
            # check if desired data type is an integer or float
            if var_type == int or var_type == float:
                try:
                    print('Converting to variable type: ' + str(var_type))
                    # convert to specified data type
                    df[var] = df[var].astype(var_type)
                except:
                    print('Could not convert to variable type: ' + str(var_type))
            else:
                print('Converting to variable type: ' + str(var_type))
                # convert to specified data type
                df[var] = df[var].astype(var_type)
        else:
            print('Converting to variable type: ' + str(var_type))
            # convert to specified data type
            df[var] = df[var].astype(var_type)
    return df

In [52]:
var_list = ['occupantsUnderTwo','occupants2to5','occupants6to18','occupants19to64']
var_type = int
drnum_county_df = clean_variables(drnum_county_df, var_list, var_type)

Variable: occupantsUnderTwo
Converting to variable type: <class 'int'>
Variable: occupants2to5
Converting to variable type: <class 'int'>
Variable: occupants6to18
Variable is an object (string)
occupants6to18
0     52707
1     10411
2      6234
3      2146
4       552
5       119
>5       45
dtype: int64
Converting to variable type: <class 'int'>
Could not convert to variable type: <class 'int'>
Variable: occupants19to64
Variable is an object (string)
occupants19to64
0      7732
1     31320
2     26961
3      4767
4      1138
5       229
>5       67
dtype: int64
Converting to variable type: <class 'int'>
Could not convert to variable type: <class 'int'>